a = input("Your last name, first name?")
b = int(input("How old are you?"))
c = input("Your phone number?")
print("Your first name, last name: ", a)
print("Your age: ", b)
print("Your phone number:", c)